import {
  siWordpress,
  siWoocommerce,
  siElementor,
  siGutenberg,
  siNextdotjs,
  siReact,
  siGraphql,
  siPhp,
  siLaravel,
  siShopify,
  siWebflow,
  siTailwindcss,
  siTypescript,
  siJavascript,
  siNodedotjs,
  siMysql,
  siMongodb,
  siJquery,
  siBootstrap,
  siGithub,
  siSanity,
  siGooglemaps,
  siGsap,
  siWhatsapp,
  siPayloadcms,
  siPrismic,
} from "simple-icons";

export type TechIcon = { title: string; hex: string; path: string };

export const techIcons: Record<string, TechIcon> = {
  WordPress: siWordpress,
  WooCommerce: siWoocommerce,
  Elementor: siElementor,
  Gutenberg: siGutenberg,
  "Next.js": siNextdotjs,
  React: siReact,
  GraphQL: siGraphql,
  PHP: siPhp,
  Laravel: siLaravel,
  Shopify: siShopify,
  Webflow: siWebflow,
  "Tailwind CSS": siTailwindcss,
  TypeScript: siTypescript,
  JavaScript: siJavascript,
  "Node.js": siNodedotjs,
  MySQL: siMysql,
  MongoDB: siMongodb,
  jQuery: siJquery,
  Bootstrap: siBootstrap,
  GitHub: siGithub,
  Sanity: siSanity,
  "Google Maps": siGooglemaps,
  GSAP: siGsap,
  WhatsApp: siWhatsapp,
  "Payload CMS": siPayloadcms,
  Prismic: siPrismic,
};
